.TH "nvmlLedState_t" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvmlLedState_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <nvml.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBcause\fP [256]"
.br
.RI "\fIIf amber, a text description of the cause. \fP"
.ti -1c
.RI "\fBnvmlLedColor_t\fP \fBcolor\fP"
.br
.RI "\fIGREEN or AMBER. \fP"
.in -1c
.SH "Detailed Description"
.PP 
LED states for an S-class unit. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
