.TH "nvmlUnitFanSpeeds_t" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvmlUnitFanSpeeds_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <nvml.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnvmlUnitFanInfo_t\fP \fBfans\fP [24]"
.br
.RI "\fIFan speed data for each fan. \fP"
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.RI "\fINumber of fans in unit. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fan speed readings for an entire S-class unit. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
