.TH "nvmlUnitInfo_t" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvmlUnitInfo_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <nvml.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [96]"
.br
.RI "\fIProduct name. \fP"
.ti -1c
.RI "char \fBid\fP [96]"
.br
.RI "\fIProduct identifier. \fP"
.ti -1c
.RI "char \fBserial\fP [96]"
.br
.RI "\fIProduct serial number. \fP"
.ti -1c
.RI "char \fBfirmwareVersion\fP [96]"
.br
.RI "\fIFirmware version. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Static S-class unit info. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
