.TH "nvmlHwbcEntry_t" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvmlHwbcEntry_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <nvml.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of HWBC entry 

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
