.TH "nvmlUnitFanInfo_t" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvmlUnitFanInfo_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <nvml.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBspeed\fP"
.br
.RI "\fIFan speed (RPM). \fP"
.ti -1c
.RI "\fBnvmlFanState_t\fP \fBstate\fP"
.br
.RI "\fIFlag that indicates whether fan is working properly. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fan speed reading for a single fan in an S-class unit. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
