.TH "Constants" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constants \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNVML_DEVICE_INFOROM_VERSION_BUFFER_SIZE\fP   16"
.br
.ti -1c
.RI "#define \fBNVML_DEVICE_UUID_BUFFER_SIZE\fP   80"
.br
.ti -1c
.RI "#define \fBNVML_SYSTEM_DRIVER_VERSION_BUFFER_SIZE\fP   80"
.br
.ti -1c
.RI "#define \fBNVML_SYSTEM_NVML_VERSION_BUFFER_SIZE\fP   80"
.br
.ti -1c
.RI "#define \fBNVML_DEVICE_NAME_BUFFER_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBNVML_DEVICE_SERIAL_BUFFER_SIZE\fP   30"
.br
.ti -1c
.RI "#define \fBNVML_DEVICE_VBIOS_VERSION_BUFFER_SIZE\fP   32"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NVML_DEVICE_INFOROM_VERSION_BUFFER_SIZE   16"
.PP
Buffer size guaranteed to be large enough for \fBnvmlDeviceGetInforomVersion\fP and \fBnvmlDeviceGetInforomImageVersion\fP 
.SS "#define NVML_DEVICE_NAME_BUFFER_SIZE   64"
.PP
Buffer size guaranteed to be large enough for \fBnvmlDeviceGetName\fP 
.SS "#define NVML_DEVICE_SERIAL_BUFFER_SIZE   30"
.PP
Buffer size guaranteed to be large enough for \fBnvmlDeviceGetSerial\fP 
.SS "#define NVML_DEVICE_UUID_BUFFER_SIZE   80"
.PP
Buffer size guaranteed to be large enough for \fBnvmlDeviceGetUUID\fP 
.SS "#define NVML_DEVICE_VBIOS_VERSION_BUFFER_SIZE   32"
.PP
Buffer size guaranteed to be large enough for \fBnvmlDeviceGetVbiosVersion\fP 
.SS "#define NVML_SYSTEM_DRIVER_VERSION_BUFFER_SIZE   80"
.PP
Buffer size guaranteed to be large enough for \fBnvmlSystemGetDriverVersion\fP 
.SS "#define NVML_SYSTEM_NVML_VERSION_BUFFER_SIZE   80"
.PP
Buffer size guaranteed to be large enough for \fBnvmlSystemGetNVMLVersion\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
