.TH "Error reporting" 3 "8 Jan 2013" "Version 1.1" "NVML" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Error reporting \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "const DECLDIR char * \fBnvmlErrorString\fP (\fBnvmlReturn_t\fP result)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This chapter describes helper functions for error reporting routines. 
.SH "Function Documentation"
.PP 
.SS "const DECLDIR char* nvmlErrorString (\fBnvmlReturn_t\fP result)"
.PP
Helper method for converting NVML error codes into readable strings.
.PP
For all products
.PP
\fBParameters:\fP
.RS 4
\fIresult\fP NVML error code to convert
.RE
.PP
\fBReturns:\fP
.RS 4
String representation of the error. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NVML from the source code.
